# Site settings
title: benn9833          # The title of your website
description:  Welcome to my website where I share information about things I'm learning. 
baseurl: ""                # Leave empty if your site is at the root of a domain (e.g., example.com)
url: "https://benn9833.github.io"  # Replace with your GitHub Pages URL

# Plugins for GitHub Pages
plugins:
  - jekyll-feed             # Optional: Provides RSS feed support
  - jekyll-seo-tag          # Optional: Adds SEO metadata to pages
  
